### ISSUE TITLE
jsbound加载方式

### ISSUE THREAD

**Issue by 507228905** [pukaicom/ReactNativeBsdiff#1]
一个android 的react native工程可以同时放俩个jsbound包，里面有两个按钮，点击不同的按钮加载不同的bound包，这样做可以吗

**Comment by pukaicom** [comment]
当然可以，初始化ReactRootView时选择不同的bundle路径就行 或者是通过 消息机制通过native向RN推送消息，通过require获取bundle Component 替换当前的Component

**Comment by pukaicom** [comment]
close
